// Generated by gencpp from file YOLO/yoloMessage.msg
// DO NOT EDIT!


#ifndef YOLO_MESSAGE_YOLOMESSAGE_H
#define YOLO_MESSAGE_YOLOMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace YOLO
{
template <class ContainerAllocator>
struct yoloMessage_
{
  typedef yoloMessage_<ContainerAllocator> Type;

  yoloMessage_()
    : data()  {
    }
  yoloMessage_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::YOLO::yoloMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::YOLO::yoloMessage_<ContainerAllocator> const> ConstPtr;

}; // struct yoloMessage_

typedef ::YOLO::yoloMessage_<std::allocator<void> > yoloMessage;

typedef boost::shared_ptr< ::YOLO::yoloMessage > yoloMessagePtr;
typedef boost::shared_ptr< ::YOLO::yoloMessage const> yoloMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::YOLO::yoloMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::YOLO::yoloMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace YOLO

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'YOLO': ['/home/user/catkin_ws/src/YOLO/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::YOLO::yoloMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::YOLO::yoloMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::YOLO::yoloMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::YOLO::yoloMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::YOLO::yoloMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::YOLO::yoloMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::YOLO::yoloMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cce5a364f3a3be12c9722c6dcad2fa94";
  }

  static const char* value(const ::YOLO::yoloMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcce5a364f3a3be12ULL;
  static const uint64_t static_value2 = 0xc9722c6dcad2fa94ULL;
};

template<class ContainerAllocator>
struct DataType< ::YOLO::yoloMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "YOLO/yoloMessage";
  }

  static const char* value(const ::YOLO::yoloMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::YOLO::yoloMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] data\n\
";
  }

  static const char* value(const ::YOLO::yoloMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::YOLO::yoloMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yoloMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::YOLO::yoloMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::YOLO::yoloMessage_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_MESSAGE_YOLOMESSAGE_H
